version: "3.8"

services:
  db:
    image: postgres:11.0-alpine
    container_name: postgres-shopper
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-shopper}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_MAX_CONNECTIONS: 2000
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      PORT: 80
      NEXT_PUBLIC_API_URL: "http://backend:8080" # URL do backend no Docker
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      PORT: 8080
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/shopper" # URL do banco de dados no Docker
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres-data:
